version: '3'

services:
  web:
    build: .
    image: loop
    container_name: loop
    command: >
      bash -c "
      chmod +x downloaddb.sh &&
      ./downloaddb.sh &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/

  redis:
    container_name: redis
    image: redis:alpine

  worker:
    build: .
    command: >
      bash -c "
      celery -A loop worker -l INFO"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis