# Generated by Django 4.2.6 on 2023-10-07 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='end_time_local',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='start_time_local',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
