# Generated by Django 4.2.6 on 2023-10-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0002_alter_businesshour_end_time_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesshour', to='store_monitor.store'),
        ),
        migrations.AlterField(
            model_name='pollstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollstore', to='store_monitor.store'),
        ),
    ]
